// Flashcards (Leitner boxes) + quiz, generated by the on-device model.
import { state, save, addXP, bus, notifyDoc, persistDoc } from './store.js';
import { chatJSON } from './llm.js';
import { $, esc, toast, busy, errMsg } from './util.js';
import { sys, CARDS_REQUEST, QUIZ_REQUEST, docLang } from './instructional.js';
import { t } from './i18n.js';

const DAY = 86400000;
const INTERVALS = [0, 1, 3, 7, 14, 30]; // days per box

const chunk = () => state.doc && state.doc.chunks?.[state.doc.current];
const shuffle = a => { for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; } return a; };

/* ---------- Flashcards (TCG-style with generated art) ---------- */
const CARD_SCHEMA = {
  type: 'object',
  properties: { cards: { type: 'array', items: { type: 'object', properties: {
    title: { type: 'string' }, front: { type: 'string' }, back: { type: 'string' }, img: { type: 'string' } },
    required: ['front', 'back'] } } },
  required: ['cards'],
};
let queue = [];

// Free, keyless, CORS-friendly image generation — one illustration per card.
function cardImgUrl(c) {
  if (!c.img) return null;
  let seed = 0;
  for (const ch of c.id || c.front) seed = (seed * 31 + ch.charCodeAt(0)) >>> 0;
  return `https://image.pollinations.ai/prompt/${encodeURIComponent(c.img + ', flat vector illustration, soft warm palette, no text')}?width=480&height=300&nologo=true&seed=${seed % 100000}`;
}

function tcgCard(c, { revealed = false } = {}) {
  const img = cardImgUrl(c);
  return `
  <div class="tcg-card${revealed ? ' revealed' : ''}">
    <div class="tcg-head"><span class="tcg-title">${esc(c.title || 'Concept')}</span><span class="tcg-box">Lv.${c.box}</span></div>
    <div class="tcg-art">${img ? `<img src="${img}" alt="" loading="lazy" onerror="this.parentElement.classList.add('no-img')">` : ''}</div>
    <div class="tcg-body">
      <div class="side">${t('cards.question')}</div>
      <p class="tcg-q">${esc(c.front)}</p>
      <div class="tcg-ans${revealed ? '' : ' hidden'}"><div class="side">${t('cards.answer')}</div>${esc(c.back)}</div>
    </div>
  </div>`;
}

function renderDeckVisual() {
  const v = $('deckVisual');
  if (!v) return;
  const cards = state.cards.slice(0, 6);
  if (!cards.length) { v.innerHTML = ''; return; }
  v.innerHTML = cards.map((c, i) => `
    <div class="mini-card" style="--r:${(i - (cards.length - 1) / 2) * 5}deg; --y:${Math.abs(i - (cards.length - 1) / 2) * 4}px">
      ${cardImgUrl(c) ? `<img src="${cardImgUrl(c)}" alt="" loading="lazy" onerror="this.remove()">` : ''}
      <span>${esc(c.title || '…')}</span>
    </div>`).join('');
}

function buildQueue() {
  queue = shuffle(state.cards.filter(c => c.due <= Date.now()));
  renderCard();
  renderDeckVisual();
}

function renderCard() {
  const stage = $('cardStage');
  if (!stage) return;
  const cc = $('cardCount');
  if (cc) cc.textContent = t('cards.count', { total: state.cards.length, due: queue.length });
  if (!state.cards.length) { stage.innerHTML = `<p class="empty-msg">${t('cards.none')}</p>`; return; }
  if (!queue.length) { stage.innerHTML = `<p class="empty-msg">${t('cards.allDone')}</p>`; return; }
  const c = queue[0];
  stage.innerHTML = tcgCard(c) + `
    <div class="rate">
      <button id="reveal" class="pill-btn">${t('cards.reveal')}</button>
      <button class="pill-btn" data-r="again" hidden>${t('cards.again')}</button>
      <button class="pill-btn" data-r="good" hidden>${t('cards.good')}</button>
      <button class="pill-btn" data-r="easy" hidden>${t('cards.easy')}</button>
    </div>`;
  $('reveal').onclick = () => {
    stage.querySelector('.tcg-ans')?.classList.remove('hidden');
    $('reveal').hidden = true;
    stage.querySelectorAll('[data-r]').forEach(b => { b.hidden = false; });
    stage.querySelector('[data-r=good]')?.focus();
  };
  stage.querySelectorAll('[data-r]').forEach(b => { b.onclick = () => rate(b.dataset.r); });
}

function rate(r) {
  const c = queue.shift();
  if (r === 'again') { c.box = 0; c.due = Date.now(); queue.push(c); }
  else {
    c.box = Math.min(5, c.box + (r === 'easy' ? 2 : 1));
    c.due = Date.now() + INTERVALS[c.box] * DAY;
    addXP(r === 'easy' ? 3 : 2);
  }
  save();
  renderCard();
}

export async function genCards({ automatic = false } = {}) {
  const ch = chunk();
  if (!ch) return toast(t('summary.needDoc'));
  const btn = $('genCards'); busy(btn, true);
  try {
    const d = state.doc;
    const data = await chatJSON([
      { role: 'system', content: sys(d) },
      { role: 'user', content: CARDS_REQUEST[docLang(d)] + ch.text },
    ], CARD_SCHEMA);
    const now = Date.now();
    const fresh = (data.cards || []).filter(c => c.front && c.back)
      .map(c => ({ id: crypto.randomUUID(), title: c.title || '', front: c.front, back: c.back, img: c.img || '', box: 0, due: now, docId: d.id, section: d.current }));
    if (!fresh.length) throw new Error(t('err.noCards'));
    state.cards.push(...fresh); save();
    buildQueue();
    if (!automatic) toast(t('cards.new', { n: fresh.length }));
    return fresh.length;
  } catch (e) { toast(errMsg(e)); } finally { busy(btn, false); }
}

/* ---------- Quiz ---------- */
const QUIZ_SCHEMA = {
  type: 'object',
  properties: { questions: { type: 'array', items: { type: 'object', properties: {
    question: { type: 'string' }, options: { type: 'array', items: { type: 'string' } },
    answer: { type: 'integer' }, explanation: { type: 'string' } },
    required: ['question', 'options', 'answer', 'explanation'] } } },
  required: ['questions'],
};
let quiz = null;

function renderQuiz() {
  const stage = $('quizStage');
  if (!quiz || !stage) return;
  if (quiz.i >= quiz.qs.length) {
    const pct = Math.round((quiz.score / quiz.qs.length) * 100);
    const passed = pct >= 60;
    if (passed && !state.doc.done.includes(state.doc.current)) {
      state.doc.done.push(state.doc.current); addXP(10); notifyDoc(); void persistDoc();
    }
    stage.innerHTML = `<h3>${t('quiz.score', { score: quiz.score, total: quiz.qs.length })}</h3>
      <p>${passed ? t('quiz.passed') : t('quiz.failed')}</p>`;
    return;
  }
  const q = quiz.qs[quiz.i];
  stage.innerHTML = `
    <div class="progressbar"><span style="width:${(quiz.i / quiz.qs.length) * 100}%"></span></div>
    <h3>${esc(q.question)}</h3>
    <div class="options">${q.options.map((o, i) => `<button class="pill-btn" data-i="${i}">${esc(o)}</button>`).join('')}</div>
    <div id="fb"></div>`;
  stage.querySelectorAll('.options button').forEach(b => {
    b.onclick = () => {
      const pick = Number(b.dataset.i), ok = pick === q.answer;
      stage.querySelectorAll('.options button').forEach((x, i) => {
        x.disabled = true;
        if (i === q.answer) x.classList.add('right');
        else if (i === pick) x.classList.add('wrong');
      });
      if (ok) { quiz.score++; addXP(5); }
      $('fb').innerHTML = `<div class="feedback"><strong>${ok ? t('quiz.correct') : t('quiz.wrong')}</strong> ${esc(q.explanation || '')}</div><button id="nextQ" class="pill-btn">${quiz.i + 1 < quiz.qs.length ? t('quiz.next') : t('quiz.result')}</button>`;
      $('nextQ').onclick = () => { quiz.i++; renderQuiz(); };
      $('nextQ').focus();
    };
  });
}

export async function genQuiz({ automatic = false } = {}) {
  const ch = chunk();
  if (!ch) return toast(t('summary.needDoc'));
  const btn = $('genQuiz'); busy(btn, true);
  try {
    const d = state.doc;
    const data = await chatJSON([
      { role: 'system', content: sys(d) },
      { role: 'user', content: QUIZ_REQUEST[docLang(d)] + ch.text },
    ], QUIZ_SCHEMA);
    const qs = (data.questions || []).filter(q => q.question && Array.isArray(q.options) && q.options.length >= 2 && q.answer >= 0 && q.answer < q.options.length)
      .map(q => {
        const opts = q.options.map((text, i) => ({ text, ok: i === q.answer }));
        shuffle(opts); // models tend to put the correct answer first
        return { question: q.question, options: opts.map(o => o.text), answer: opts.findIndex(o => o.ok), explanation: q.explanation };
      });
    if (!qs.length) throw new Error(t('err.noQuiz'));
    quiz = { qs, i: 0, score: 0 };
    renderQuiz();
    return qs.length;
  } catch (e) { toast(errMsg(e)); } finally { busy(btn, false); }
}

export async function generateLearningTools() {
  const [cards, quizResult] = await Promise.allSettled([
    genCards({ automatic: true }),
    genQuiz({ automatic: true }),
  ]);
  return {
    cards: cards.status === 'fulfilled' ? cards.value : 0,
    quiz: quizResult.status === 'fulfilled' ? quizResult.value : 0,
  };
}

export function initStudy() {
  const gc = $('genCards'), gq = $('genQuiz');
  if (gc) gc.onclick = () => genCards();
  if (gq) gq.onclick = () => genQuiz();
  bus.addEventListener('doc', () => {
    quiz = null;
    const qs = $('quizStage');
    if (qs) qs.innerHTML = `<p class="empty-msg">${t('quiz.empty')}</p>`;
    buildQueue();
  });
  buildQueue();
}
